kind: Cluster
apiVersion: kind.x-k8s.io/v1beta1
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80   # Porta del container (nel nodo)
        hostPort: 80        # Porta dell'host (esterna)
        protocol: TCP
      - containerPort: 443  # Porta del container (nel nodo)
        hostPort: 443       # Porta dell'host (esterna)
        protocol: TCP
