kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80   # Porta utilizzata dall'Ingress Controller (HTTP)
        hostPort: 80        # Porta esposta sull'host
        protocol: TCP
      - containerPort: 443  # Porta utilizzata dall'Ingress Controller (HTTPS)
        hostPort: 443       # Porta esposta sull'host
        protocol: TCP
    labels:                 # Etichette per il nodo
      ingress-ready: "true" # Etichetta per il nodo utilizzato dall'Ingress Controller
